# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "cf824063-ecba-42b4-96b4-fb06c7ea119d"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Submit a new Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh
    #increment_build_number({
    #  build_number: latest_testflight_build_number + 1
    #})
    increment_build_number(xcodeproj: './ios/WaterRangers.xcodeproj') # Increment the build number
    gym(scheme: "WaterRangers", project: './ios/WaterRangers.xcodeproj') # Build the app
    pilot(skip_submission: true) # Upload the app to TestFlight
  end

  after_all do |lane|
    slack(channel: "development", message: "Successfully deployed new Water Rangers Beta update to TestFlight.")
  end
end

platform :android do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    gradle(task: 'clean', project_dir: "android/") # Clean the Gradle project
    gradle(task: "assemble", build_type: "Release", project_dir: "android/") # Build the Release APK
    supply(track: "beta", apk: "android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)
  end

  after_all do |lane|
    slack(channel: "development", message: "Successfully deployed new Water Rangers Beta update to the Play Store.")
  end
end